name: python version benchmarker

on:
  push:
    branches: [main]


jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: 3.7
      - uses: py-actions/py-dependency-install@v2
        with: 
          path: requirements.txt
      - name: run pylint, fail under 8.5
        run: pip install pylint; pylint benchmarker.py

  benchmark:
    runs-on: ubuntu-latest
    needs: pylint
    outputs:
      pypy2: ${{ steps.result.outputs.pypy2 }}
      pypy3: ${{ steps.result.outputs.pypy3 }}
      py2-7: ${{ steps.result.outputs.py2-7 }}
      py3-6: ${{ steps.result.outputs.py3-6 }}
      py3-7: ${{ steps.result.outputs.py3-7 }}
      py3-8: ${{ steps.result.outputs.py3-8 }}
    strategy:
      matrix:
        include:
          - python-version: pypy2
            out: pypy2
          - python-version: pypy3
            out: pypy3
          - python-version: 2.7
            out: py2-7
          - python-version: 3.6
            out: py3-6
          - python-version: 3.7
            out: py3-7
          - python-version: 3.8
            out: py3-8
    
    steps:
      - uses: actions/checkout@v2
      - name: setup py
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: save benchmark stats
        id: result
        run: |
          echo "::set-output name=${{matrix.out}}::$(python benchmarker.py)"

  pastebin:
    runs-on: ubuntu-latest
    needs: benchmark
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9          
      - uses: py-actions/py-dependency-install@v2
        with: 
          path: requirements.txt
      - name: use benchmark data
        run: echo '${{ toJSON(needs.benchmark.outputs) }}' > matrix-outputs.json
      - name: pastebin API request
        env:
          PASTEBIN_API_KEY: ${{ secrets.PASTEBIN_API_KEY }}
        run: python pastebin.py
      - name: upload newly created artifact
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-stats
          path: newpaste.txt
